### ISSUE TITLE
Specify the classes the block editor uses (for e.g image full width)

### ISSUE THREAD

**Issue by Newnab** [EtchUK/Etch.OrchardCore.Blocks#15]
Currently the block editor outputs `figure figure--stretched` on full width images, which doesn't quite align with our boilerplate's existing styles for full width images. Is there a way we can override this when implementing the blocks?

**Comment by peterkeating** [comment]
@Newnab Yea! If you add a "Block-Image.cshtml" (or you can use Liquid if you prefer) in to your theme that will override the output of an image block. 

Here is the template used by default - https://github.com/EtchUK/Etch.OrchardCore.Blocks/blob/master/Views/Block-Image.cshtml
