### ISSUE TITLE
Should we render ids on block headings as we've done for Heading widgets?

### ISSUE THREAD

**Issue by DannyT** [EtchUK/Etch.OrchardCore.Blocks#20]
I.e. apply what we did here: https://github.com/EtchUK/Etch.OrchardCore.Widgets/pull/32

To here: https://github.com/EtchUK/Etch.OrchardCore.Blocks/blob/master/Views/Block-Heading.cshtml

**Comment by DannyT** [comment]
An alternative/addition could be a new "Anchor Block" which you just give a name to and it renders an invisible element that can be linked to. It's more work for the user to have to create a specific block but allows more control over exactly where you anchor to...

**Comment by peterkeating** [comment]
Had the exact same thought last night but forgot to do it!
